spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notifier
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
notification:
  default:
    expiry: 5