package com.demo.notificationproducer.models.enums;

public enum OfficeType
{
	DISTRICT_EDUCATION_OFFICE,
	UPAZILA_EDUCATION_OFFICE,
	ZONAL_OFFICE,
	PROJECT,
	TRAINING_CENTER,
	CELL,
	SECTION,
	WING,
	EDUCATION_BOARD,
	UNKNOWN
}
